src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Serializable; // edit upload

#[ORM\Entity(repositoryClass: UserRepository::class)]

#[Vich\Uploadable]
class User implements UserInterface, PasswordAuthenticatedUserInterface, Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Vich\UploadableField(mapping: 'user', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: News::class)]
    private Collection $news;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Like::class)]
    private Collection $likes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: SpectacleComments::class)]
    private Collection $spectacleComments;

    public function __construct()
    {
        $this->news = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->spectacleComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }


    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }


    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return Collection<int, News>
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(News $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news->add($news);
            $news->setAuthor($this);
        }

        return $this;
    }

    public function removeNews(News $news): self
    {
        if ($this->news->removeElement($news)) {
            // set the owning side to null (unless already changed)
            if ($news->getAuthor() === $this) {
                $news->setAuthor(null);
            }
        }

        return $this;
    }

    public function serialize()
    {

        return serialize([
            $this->id,
            $this->email,
            $this->password,
        ]);
    }

    public function unserialize(string $data)
    {
        [
            $this->id,
            $this->email,
            $this->password,
        ] = unserialize($data);
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, SpectacleComments>
     */
    public function getSpectacleComments(): Collection
    {
        return $this->spectacleComments;
    }

    public function addSpectacleComment(SpectacleComments $spectacleComment): self
    {
        if (!$this->spectacleComments->contains($spectacleComment)) {
            $this->spectacleComments->add($spectacleComment);
            $spectacleComment->setUser($this);
        }

        return $this;
    }

    public function removeSpectacleComment(SpectacleComments $spectacleComment): self
    {
        if ($this->spectacleComments->removeElement($spectacleComment)) {
            // set the owning side to null (unless already changed)
            if ($spectacleComment->getUser() === $this) {
                $spectacleComment->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\EditProfilePictureType;
use App\Form\EditProfileType;
use App\Repository\CommentsRepository;
use App\Repository\SpectacleCommentsRepository;
use App\Repository\TicketsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    #[Route('/profile', name: 'app_profile')]
    public function profile(\Symfony\Component\HttpFoundation\Request $request, EntityManagerInterface $manager,
                            CommentsRepository $commentsRepository, TicketsRepository $ticketsRepository,
                            SpectacleCommentsRepository $spectacleCommentsRepository):
    Response
    {
        $user = $this->getUser();
        $user_id = $user->getId();
        $form = $this->createForm(EditProfileType::class, $user);
        $form->handleRequest($request);
        $comments = $commentsRepository->findBy(['user' => $user_id]);
        $spectacle_comments = $spectacleCommentsRepository->findBy(['user' => $user_id]);
        $profile_picture_form = $this->createForm(EditProfilePictureType::class, $user);
        $profile_picture_form->handleRequest($request);
        $tickets = $ticketsRepository->findBy(['user' => $user_id]);
        if($form->isSubmitted() && $form->isValid()) {
            $user->setUpdatedAt(new \DateTimeImmutable());
            $manager->flush();
            $this->addFlash('success', "Profil modifié avec succès!");
            return $this->redirectToRoute('app_profile');
        }
        if($profile_picture_form->isSubmitted() && $profile_picture_form->isValid()) {
            $user->setUpdatedAt(new \DateTimeImmutable());
            $manager->flush();
            $this->addFlash('success', "Photo de profil modifiée avec succès!");
            if($user->getImageName() == null){
                $user->setImageName('default.jpg');
            }
            return $this->redirectToRoute('app_profile');
        }
        return $this->renderForm('user/profile.html.twig', [
            'form' => $form,
            'profile_picture_form' => $profile_picture_form,
            'comments' => $comments,
            'spectacle_comments' => $spectacle_comments,
            'tickets' => $tickets,
        ]);
    }

}

templates/user/edit-profile.html.twig
{% extends('base.html.twig') %}

{% block body %}
    <div class="container my-4">
        <section class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="display-4">Modifier votre compte</h2>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button type="submit" class="btn btn-outline-dark">Enregistrer les modifications</button>
                {{ form_end(form) }}
            </div>
        </section>
    </div>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/profile.css') }}">
{% endblock %}
{% block title %}Votre profil{% endblock %}

{% block body %}
    <main class="container-fluid profile">
        <div class="container profile-container">
            <div class="row">
                <div class="col-12 profile-section">
                    <h1 class="text-center mt-3 mb-4">Votre profil</h1>
                    <hr>
                    <div class="row mb-5 justify-content-center">
                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 profile-picture
                        justify-content-center text-center mt-4">
                            <img src="assets/img/user/{{ app.user.imageName }}" alt="{{ app.user.firstName }} {{ app
                            .user.lastName }} " class="img-profile">
                            <div class="row justify-content-center">
                                <div class="accordion col-6 mt-4" id="accordionExample">
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="headingOne">
                                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                Modifier votre photo de profil
                                            </button>
                                        </h2>
                                        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                            <div class="accordion-body">
                                                {{ form_start(profile_picture_form) }}
                                                {{ form_row(profile_picture_form.imageFile) }}
                                                <button type="submit" class="btn btn-outline-light mt-4"
                                                        style="color: black">Enregistrer les
                                                    modifications</button>
                                                {{ form_end(profile_picture_form) }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 profile-data">
                            <div class="col-12">
                                <div class="row justify-content-center mt-5 mb-5">
                                    <h3 class="text-center">Informations</h3>
                                    <div class="col-8 mt-5">
                                        <h4 class="mb-3"><b>Prénom: &nbsp;&nbsp;</b> <i>{{ app.user.firstName }}</i></h4>
                                        <h4 class="mb-3"><b>Nom: &nbsp;&nbsp;</b> <i>{{ app.user.lastName }}</i></h4>
                                        <h4 class="mb-3"><b>Email: &nbsp;&nbsp;</b> <i>{{ app.user.email }}</i></h4>
                                        <h4 class="mb-3"><b>Date d'inscription: &nbsp;&nbsp;</b> <i>{{ app.user.createdAt|date('d/m/Y') }}</i></h4>
                                        <h4 class="mb-3"><b>Role: &nbsp;&nbsp;</b>
                                            {% if is_granted('ROLE_SUPER_ADMIN') %}
                                                <i>Super Administrateur</i>
                                            {% elseif is_granted('ROLE_ADMIN') %}
                                                <i>Administrateur</i>
                                            {% elseif is_granted('ROLE_USER') %}
                                                <i>Utilisateur standard</i>
                                            {% endif %}
                                        </h4>
                                        <a href="#"><button class="btn btn-outline-light mb-5">Changer mon mot de
                                                passe</button></a>

                                        <div class="accordion" id="accordionExample">
                                            <div class="accordion-item">
                                                <h2 class="accordion-header" id="headingTwo">
                                                    <button class="accordion-button" type="button"
                                                            data-bs-toggle="collapse" data-bs-target="#collapseTwo"
                                                            aria-expanded="true" aria-controls="collapseTwo">
                                                        Modifier vos informations
                                                    </button>
                                                </h2>
                                                <div id="collapseTwo" class="accordion-collapse collapse"
                                                     aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                                    <div class="accordion-body">
                                                        {{ form_start(form) }}
                                                        {{ form_widget(form) }}
                                                        <button type="submit" class="btn btn-outline-dark">Enregistrer les modifications</button>
                                                        {{ form_end(form) }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-lg-6 profile-section">
                            <h1 class="text-center mb-4" style="margin-top: -100px">Vos commentaires</h1>
                            <hr>
                            {% for comment in comments %}
                                <div class="d-flex justify-content-center row">
                                    <div class="col-md-10 mt-3">
                                        <div class="d-flex flex-column comment-section">
                                            <div class="bg-black p-2">
                                                <div class="d-flex flex-row user-info"><img
                                                            class="comment-author-img" src="{{ asset
                                                        ('assets/img/news/' ~ comment.news.imageName) }}"
                                                            width="40">
                                                    <div class="d-flex flex-column justify-content-start
                                                        ml-2"><span class="d-block font-weight-bold
                                                        name"><b>{{ comment.news.title }}</b> </span><span class="date
                                                        text-white">{{ comment.createdAt|date('d/m/Y h:m')
                                                            }}</span></div>
                                                </div>
                                                <div class="mt-2">
                                                    <p class="comment-text">{{ comment.content|raw }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            {% for spectacle_comment in spectacle_comments %}
                                <div class="d-flex justify-content-center row">
                                    <div class="col-md-10 mt-3">
                                        <div class="d-flex flex-column comment-section">
                                            <div class="bg-black p-2">
                                                <div class="d-flex flex-row user-info"><img
                                                            class="comment-author-img" src="{{ asset
                                                        ('assets/img/spectacles/' ~ spectacle_comment.spectacle
                                                        .imageName) }}"
                                                            width="40">
                                                    <div class="d-flex flex-column justify-content-start
                                                        ml-2"><span class="d-block font-weight-bold
                                                        name"><b>{{ spectacle_comment.spectacle.titre }}</b>
                                                        </span><span class="date
                                                        text-white">{{ spectacle_comment.createdAt|date('d/m/Y h:m')
                                                            }}</span></div>
                                                </div>
                                                <div class="mt-2">
                                                    <p class="comment-text">{{ spectacle_comment.content|raw }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-12 col-lg-6 profile-section">
                            <h1 class="text-center mb-4" style="margin-top: -100px">Vos tickets</h1>
                            <hr>
                            {% for ticket in tickets %}
                                <div class="justify-content-center row">
                                    <div class="col-md-12 mt-3">
                                        <div class="d-flex flex-column comment-section">
                                            <div class="bg-black p-2">
                                                <div class="col-12 flex-row user-info">
                                                    <div class="d-flex flex-column justify-content-start ml-2">
                                                        <a href="{{ asset('tickets/' ~ ticket.file )  }}" target="_blank" >
                                                            <button class="btn btn-secondary btn-lg col-12">
                                                                <i class="icofont-ticket display-2"></i>
                                                                <span class="d-block font-weight-bold
                                                        name"><b>{{ ticket.spectacle.titre }}</b>
                                                        </span>
                                                                <span
                                                                        class="date
                                                        text-white">{{ ticket.purchasedAt|date('d/m/Y h:m:s') }}
                                                        </span>
                                                            </button>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}